### ISSUE TITLE
Question about adding a custom RPC stack

### ISSUE THREAD

**Issue by obedmr** [google/distbench#103]
I'm interested on adding a custom RPC stack to be executed with distbench, is there a template or file you would recommend to take a look for starting?

**Comment by oserres** [comment]
We tried to make that easy; you just need to write a new protocol_driver, for a template of the functions to implement look at protocol_driver.h and as examples see:
- protocol_driver_grpc.{h,cc}
- pull request https://github.com/google/distbench/pull/79 (implementing the Mercury rpc stack)
- pull request https://github.com/google/distbench/pull/28 (for Apache Thrift)

Don't foget to add your new protocol_driver to protocol_driver_allocator.

Please consider sending a pull-request for your new protocol driver if you think it will be useful to others.

**Comment by obedmr** [comment]
This is great, thanks a lot @oserres, will start then on those files and PRs
