### ISSUE TITLE
simple_test fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by AjitDingankar** [google/distbench#20]
I'm new to gRPC, so this may be a "user error" and not a real issue. 

On a freshly installed Ubuntu 18.04.5 LTS, I followed the instructions in: 
https://github.com/google/distbench/blob/main/docs/getting-started.md 

I started a test_sequencer and a node_manager on localhost manually.
```bash
bazel run :distbench -- test_sequencer &
bazel run :distbench -- node_manager --test_sequencer=localhost:10000 --port=9999 &
```
I checked that they are running. 
```bash
$ sudo netstat -ltnp | grep distbench
tcp6       0      0 :::9999                 :::*                    LISTEN      45149/distbench
tcp6       0      0 :::10000                :::*                    LISTEN      44538/distbench

```

However, I noticed the following error when I run `./simple_test.sh`
```bash
Failed! ((grpc::status: failed to connect to all addresses)
```

**Comment by AjitDingankar** [comment]
I also ran `start_distbench_localhost.sh` after killing the processes that I had started earlier manually. 
It ends with console output:  
```bash
I20210731 14:06:31.600041 48153 distbench_test_sequencer.cc:125] node node0 was already idle
DistBench is running.
Try running simple_test.sh to give it a test to execute.
```

Now there is more output at the end of `./simple_test.sh`
```bash
I20210731 14:07:26.748265 48153 distbench_test_sequencer.cc:125] node node0 was already idle
I20210731 14:07:26.748328 48153 distbench_test_sequencer.cc:233] All services placed manually
I20210731 14:07:26.748340 48153 distbench_test_sequencer.cc:278] Service Placement:
I20210731 14:07:26.748351 48153 distbench_test_sequencer.cc:280] node0:
I20210731 14:07:26.748361 48153 distbench_test_sequencer.cc:282]   leaf/0
I20210731 14:07:26.748371 48153 distbench_test_sequencer.cc:282]   leaf/1
I20210731 14:07:26.748380 48153 distbench_test_sequencer.cc:282]   leaf/2
I20210731 14:07:26.748390 48153 distbench_test_sequencer.cc:282]   load_balancer/0
I20210731 14:07:26.748399 48153 distbench_test_sequencer.cc:282]   root/0
I20210731 14:07:26.757014 48153 distbench_test_sequencer.cc:361] Finished AsyncConfigureNode status:UNAVAILABLE: failed to connect to all addresses
Failed! (grpc::status: failed to connect to all addresses)
```

Hope this helps in debugging!

**Comment by AjitDingankar** [comment]
I tried to test gRPC helloworld and got the "same" error except that I also saw the 
error code (14). I fixed the issue by adding `localhost` to the `no_proxy` env variable. 

However, the distbench errors didn't go away, so I cloned the distbench repo again, 
tried the build and ran the unit tests. I found that `test_sequencer` test failed: 
```bash
//:distbench_engine_test                                                 PASSED in 0.3s
//:protocol_driver_test                                                  PASSED in 0.3s
//:distbench_test_sequencer_test                                         FAILED in 71.2s
```
In particular, the `clique` test had failed. Output of `grep RUN test.log` shows:
```bash
[ RUN      ] DistBenchTestSequencer.ctor
[ RUN      ] DistBenchTestSequencer.init
[ RUN      ] DistBenchTestSequencer.empty_group
[ RUN      ] DistBenchTestSequencer.nonempty_group
[ RUN      ] DistBenchTestSequencer.100k_grpc
[ RUN      ] DistBenchTestSequencer.100k_grpc_async_callback
[ RUN      ] DistBenchTestSequencer.clique_test
[ RUN      ] DistBenchTestSequencer.stochastic_test
[ RUN      ] DistBenchTestSequencer.protocol_driver_options_test
```
The output for `grep FAIL test.log` is:
```bash
[  FAILED  ] DistBenchTestSequencer.clique_test (15037 ms)
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DistBenchTestSequencer.clique_test
 1 FAILED TEST
```

**Comment by oserres** [comment]
Hi Ajit,
Thanks for reporting the bug and the no_proxy fix. I will add a FAQ with that workaround.
For the clique test failing; could you save the output of `make testlog` and send it to me by email ?

**Comment by AjitDingankar** [comment]
Thanks, Olivier! I've sent you an email. 

BTW, the no_proxy fix didn't really work for distbench (it only worked for the gRPC helloworld).

**Comment by oserres** [comment]
I added a FAQ in #21 which recommend un-setting the proxies; I think that should be the workaround for your issue.

**Comment by oserres** [comment]
Closing as FAQ has been merged.
